### PR TITLE
adds support for deadlines and scheduled

### PR DESCRIPTION
**Pull request by rbenson**
adds support for DEADLINE: <yyyy-mm-dd> (emac format) with the option of showing 3 char day (ex Fri)

### CODE REVIEW

**Comment by danielmagnussons** [comment]
Hi, can you add a one liner in install.org on how to use this? The idea for install.org is to list what is currently working

https://github.com/danielmagnussons/orgmode/blob/master/messages/install.org

**Comment by rbenson** [comment]
Where were you thinking? Install.org doesn't hav

**Comment by rbenson** [comment]
oops got tab happy, but the install doesn't have theme related information, This extends the language to allow coloring for DEADLINE: <date> SCHEDULED: <date>. See https://github.com/rbenson/SublimeText/blob/master/orgmode/Om.jpg

**Comment by danielmagnussons** [comment]
Ah nice, your screenshots explains the feature very well. Just add "DEADLINE:<date> SCHEDULED:<date>"  in install.org.  The idea is that people that install orgmode will see this file and see what colors and misc other features it supports when orgmode syntax is enabled.

"Context sensitive highlighting" in install.org have similar features listed with coloring.

**Pull request merged**
